import { createApp } from 'vue'
import './style.css'
import 'primeicons/primeicons.css'
import Aura from '@primeuix/themes/aura'
import PrimeVue from 'primevue/config'
import App from './App.vue'

const primeVueKoreanLocale = {
  startsWith: '시작',
  contains: '포함',
  notContains: '포함하지 않음',
  endsWith: '끝',
  equals: '같음',
  notEquals: '같지 않음',
  noFilter: '필터 없음',
  lt: '보다 작음',
  lte: '작거나 같음',
  gt: '보다 큼',
  gte: '크거나 같음',
  dateIs: '날짜 같음',
  dateIsNot: '날짜 다름',
  dateBefore: '이전 날짜',
  dateAfter: '이후 날짜',
  clear: '초기화',
  apply: '적용',
  matchAll: '모두 일치',
  matchAny: '하나 이상 일치',
  addRule: '규칙 추가',
  removeRule: '규칙 삭제',
  accept: '예',
  reject: '아니오',
  choose: '선택',
  upload: '업로드',
  cancel: '취소',
  completed: '완료',
  pending: '대기',
  fileSizeTypes: ['B', 'KB', 'MB', 'GB', 'TB', 'PB', 'EB', 'ZB', 'YB'],
  dayNames: ['일요일', '월요일', '화요일', '수요일', '목요일', '금요일', '토요일'],
  dayNamesShort: ['일', '월', '화', '수', '목', '금', '토'],
  dayNamesMin: ['일', '월', '화', '수', '목', '금', '토'],
  monthNames: ['1월', '2월', '3월', '4월', '5월', '6월', '7월', '8월', '9월', '10월', '11월', '12월'],
  monthNamesShort: ['1월', '2월', '3월', '4월', '5월', '6월', '7월', '8월', '9월', '10월', '11월', '12월'],
  chooseYear: '연도 선택',
  chooseMonth: '월 선택',
  chooseDate: '날짜 선택',
  prevDecade: '이전 10년',
  nextDecade: '다음 10년',
  prevYear: '이전 연도',
  nextYear: '다음 연도',
  prevMonth: '이전 달',
  nextMonth: '다음 달',
  prevHour: '이전 시간',
  nextHour: '다음 시간',
  prevMinute: '이전 분',
  nextMinute: '다음 분',
  prevSecond: '이전 초',
  nextSecond: '다음 초',
  am: '오전',
  pm: '오후',
  today: '오늘',
  weekHeader: '주',
  firstDayOfWeek: 0,
  showMonthAfterYear: true,
  dateFormat: 'yy-mm-dd',
  weak: '약함',
  medium: '보통',
  strong: '강함',
  passwordPrompt: '비밀번호 입력',
  emptyFilterMessage: '결과 없음',
  searchMessage: '{0}개의 결과가 있습니다',
  selectionMessage: '{0}개 선택됨',
  emptySelectionMessage: '선택 없음',
  emptySearchMessage: '결과 없음',
  emptyMessage: '옵션 없음',
  fileChosenMessage: '{0}개 파일',
  noFileChosenMessage: '선택된 파일 없음',
  aria: {
    trueLabel: '참',
    falseLabel: '거짓',
    nullLabel: '선택 안 됨',
    close: '닫기',
    previous: '이전',
    next: '다음',
    navigation: '탐색',
    selectAll: '전체 선택',
    unselectAll: '전체 선택 해제',
  },
}

createApp(App)
  .use(PrimeVue, {
    locale: primeVueKoreanLocale,
    theme: {
      preset: Aura,
      options: {
        darkModeSelector: false,
      },
    },
  })
  .mount('#app')
